### ISSUE TITLE
SDK is deprecated. 

### ISSUE THREAD

**Issue by godenasai** [RobertWalsh/usergrid-swift#1]
When I use applyPushToken, I am receiving the error below

Response Description: {
  "error" : "api.usergrid.com is deprecated; see the following for more details: https:\/\/community.apigee.com\/articles\/34480\/new-api-baas-trial.html"
}.

Can someone point me to the right SDK. URGENT.

**Comment by RobertWalsh** [comment]
The default API url has been deprecated.  

Until I can get a new version posted you can use the new API url endpoint "https://apibaas-trial.apigee.net" when initializing the client like so:

```
let config = UsergridClientConfig(orgId: "orgId", appId: "appId", baseUrl: "https://apibaas-trial.apigee.net")

Usergrid.initSharedInstance(configuration: config)
```

**Comment by godenasai** [comment]
@RobertWalsh Thanks man! I did that. Its working.
